#!/bin/sh

set -eox pipefail

export network="$1"
api_key="$2"
reporters="$3"

if [ -z "$network" -o -z "$api_key" ]; then
  echo "script/deploy [network] [etherscan_api_key] [reporters]";
  exit 1;
fi

npx saddle compile
npx saddle deploy OpenOraclePriceData -n "$network"
sleep 15; # allow Etherscan time to see contract
data_addr=`node -e "const contracts = require('./.build/${network}.json'); console.log(contracts.OpenOraclePriceData);"`
npx saddle verify "$api_key" "$data_addr" OpenOraclePriceData -n "$network" -vvv

npx saddle deploy AnchoredView "$data_addr" "$reporter" "$anchor_address" "$anchor_tolerance_mantissa" "$ctokens":struct -n "$network"
sleep 15; # allow Etherscan time to see contract
view_addr=`node -e "const contracts = require('./.build/${network}.json'); console.log(contracts.AnchoredView);"`
npx saddle verify "$api_key" "$view_addr" AnchoredView "$data_addr" "$reporter" "$anchor_address" "$anchor_tolerance_mantissa" "$ctokens":struct -n "$network"
